### PR TITLE
Add lodash to jshint globals

### PR DESCRIPTION
**Pull request by ssured**

### CODE REVIEW

**Comment by toddjordan** [comment]
thanks @ssured but I'm wondering why this is necessary since lodash is specified in the global `.jshintrc` file in the project root.

**Comment by ssured** [comment]
Maybe due to inheritance rules of ember-cli this pops up? I did not investigate further, I'll close it this for now

**Comment by toddjordan** [comment]
Are you seeing failed ember jshint test cases?

**Comment by ssured** [comment]
Yes, I had them. Maybe something broke on my machine, as I had a hard time making a sandbox project to test this plugin. Or maybe something changed in the recent ember-cli?

**Comment by toddjordan** [comment]
hmm.  looks like the last build failed for canary (which I allow it to), but it passed for beta: https://travis-ci.org/toddjordan/ember-cli-dynamic-forms/builds/157265382

**Pull request closed without merging**
