### PR TITLE
Upgrade to 2.2.0-beta.1

### PR DESCRIPTION
**Pull request by toddjordan**

### CODE REVIEW

**Comment by jeremywrowe** [comment]
Is the minimum target for this going to be ember 2.0?

**Comment by toddjordan** [comment]
Good Question... I'm torn between backward compatibility and using ember new stuff. I could create a branch for 1.13 but then we'd have to dual maintain, which doesn't seem like a good cost/benefit right now.  Maybe for new we stay as is and I'll just keep this branch around and keep it at the latest ember.  What are your thoughts?

**Comment by jeremywrowe** [comment]
Yeah, let's move forward on the 2.* series and back port if necessary

**Comment by toddjordan** [comment]
Cool.  I see that beta 2 came out last week.  I'll jump it to that and then we can merge.

**Pull request merged**
